docPersonalOverlayTemplate = "<div id='mainOverlay'>"
								+"<div class='leftDiv left'><img src={{img_src}} alt='Doctors image' /></div>"
								+"<div class='rightDiv right'><h1>{{firstName}} {{lastName}} {{designation}}</h1>"
								+"<div class='briefInfo'> {{breifInfo}}</div>"
								+"<table id='details_table' >"
									+"<tr>"
										+"<td>SPECIALITY</td>"
										+"<td>{{speciality}}</td>"
									+"</tr>"
									+"<tr>"
										+"<td>CLINIC</td>"
										+"<td>{{clinic}}</td>"
									+"</tr>"
									+"<tr>"
										+"<td>LOCATION</td>"
										+"<td>{{location}}</td>"
									+"</tr>"
									+"<tr>"
										+"<td>LANGUAGES</td>"
										+"<td>{{languages}}</td>"
									+"</tr>"
								+"</table>"
								+"<ul id='gred_details'>"
									+"<li><span>Experience</span>"
										+"<span>{{experience}}</span></li>"
									+"<li><span>Certified by us</span>"
										+"<span>{{certified}}</span></li>"
									+"<li><span>Board Certified</span>"
										+"<span>{{boardCertified}}</span></li>"
									+"<li><span>Clininc Accreditation</span>"
										+"<span>{{accreditation}}</span></li>"
								+"</ul>"
								+"</div>"
								+"<div class='clearAll'></div>"
								+"<div>"
									+"<h2>PROCEDURE FOCUS</h2>"
									+"<p class='font-16'>{{procedureFocus}}</p>"
								+"</div>"
								+"<div>"
									+"<h2>CLINICAL FOCUS</h2>"
									+"<p class='font-16'>{{clinicalFocus}}</p>"
								+"</div>"
								+"<div>"
									+"<h1 class='font-32'> Hospital Details</h1>"
									+"<h2 class='bold'>{{hospitalName}}</h2>"
									+"<p class='left hospitalDetails font-16'>{{hospitalDetails}}</p>"
									+"<img src={{hospitalImg}} alt='hospital pic' class='right hospitalImg'/>"									
								+"</div>"
								+"<div class='clearAll'></div>"
								+"<div>"
									+"<h1 class='font-32'>Qualifications</h1>"
									+"<h2 class='font-18'>LICENSE NUMBER</h2>"
									+"<p class='font-16'>{{licenseNumber}}</p>"
								+"</div>"
								+"<ul>{{#hasCertifications}}<h2 class='font-18'>CERTIFICATIONS</h2>{{/hasCertifications}}{{#certifications}}<li>{{.}}</li>{{/certifications}}</ul>"
								+"<ul>{{#hasTraining}}<h2 class='font-18'>POST GRADUATE MEDICAL TRAINING</h2>{{/hasTraining}}{{#training}}<li>{{.}}</li>{{/training}}</ul>"
								+"<ul>{{#hasMedicalSchools}}<h2 class='font-18'>MEDICAL SCHOOL</h2>{{/hasMedicalSchools}}{{#medicalSchools}}<li>{{.}}</li>{{/medicalSchools}}</ul>"
								+"<ul>{{#isMember}}<h2 class='font-18'>MEMBERSHIP</h2>{{/isMember}}{{#memberships}}<li>{{.}}</li>{{/memberships}}</ul>"
							+"</div>";
							